### ISSUE TITLE
Suggested Updates ♻️ 

### ISSUE THREAD

**Issue by brytebee** [yaseerokino/javascript-capstone#29]
Hi! Team, 👋 

You have done an amazing job so far. Well done! 👍.

However, we have a few suggested changes.

1. You should add a snapshot of the project.
2. You should add a live link.
3. You should update the name of the Authors on the Readme file.

Good luck and happy hacking 😃 😄 👩‍💻

**Comment by ookino** [comment]
Thank you for the suggestions, i will work on it
